0x2E/fusion

api/group.go, frontend/src/lib/api/group.ts, frontend/src/lib/opml.ts, frontend/src/routes/(authed)/feeds/ActionAdd.svelte, frontend/src/routes/(authed)/feeds/ActionOPML.svelte, frontend/src/routes/+layout.svelte, model/feed.go, repo/feed.go, repo/repo.go, server/feed.go, server/group.go, server/group_form.go
1. Parse the groups within OPML. Flatten the multidimensional group to a one-dimensional structure, using a naming convention like 'a/b/c'.
2. Create any non-existent groups.
3. Import feeds into the corresponding group.
=> feat: create groups and import feeds into them, based on opml

Dockerfile
As documented in the OCI Image Format, [org.opencontainers.image.source](https://github.com/opencontainers/image-spec/blob/5325ec48851022d6ded604199a3566254e72842a/annotations.md#L24) identifies an image's source repository. This is purely for documentation purposes. It does however help tools such as [Renovate](https://docs.renovatebot.com/modules/datasource/docker/#description) to find the changelogs when a new Fusion version is released. The changelogs would then be included in the PR Renovate creates.
=> Set org.opencontainers.image.source label in Dockerfile

scripts.sh
The set -e option tells /bin/sh to exit immediately when any command terminates with a failing exit code. Using this option allows us to simplify a lot of the logic and remove the && and || exit 1 clauses because they're not necessary with set -e.
Further details on `set -e`: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#set
=> Use the set -e option in scripts.sh

Dockerfile, scripts.sh
Docker currently duplicates the build logic from scripts.sh. It's not a big deal now because it's only a couple of standard lines, but if we want to customize the build in the future, it will be useful to have a single, authoritative build script that all build paths use.
=> Use scripts.sh to build within Docker

scripts.sh
By default, Go builds with dynamic linking. This has the benefit of allowing the compiled binary to re-use existing libraries on the system, but the drawback is that the binary is less portable, as it won't run on systems that lack the libraries it expects. For example, [the precompiled Fusion binary](https://github.com/0x2E/fusion/releases/tag/v0.8.9) does not run on my NixOS 24.11 system.
Switching to static linking means that fusion can basically run on any Linux system regardless of what libraries are installed. It also will allow us to [change the base Docker image from debian to alpine](https://github.com/0x2E/fusion/commit/9f460a44f83d34266e8bfb880dc0727ca2c99662), resulting in an image that's about 80% smaller:
```text
REPOSITORY              TAG       IMAGE ID       CREATED …
```
=> Build backend using static linking

.env.example, .gitignore, README.md, conf/conf.go
It caught me by surprise during development that fusion was reading environment variables from .env, as that's not really clear anywhere.
I think it's a bit of a gotcha, so I added logging to make the behavior clearer, and I renamed the default .env file to .env.example so that the user has to explicitly choose to use a .env file.
Keeping the real .env file out of source control also protects developers from accidentally committing their real password to source control and leaking it by mistake.
=> Rename .env to .env.example

api/session.go
We're using a 'magic string' for the echo session key name, which makes it easy for the different instances of the string to go out of sync. Using a named constant makes the intent clear and ensures all copies of the key name in the code stay in sync.
=> Use a constant for the session key name

Dockerfile, scripts.sh
Because of #36 and #37, fusion no longer needs an environment that provides glibc. Because of that, we can switch to the slimmer Alpine Linux base image for the Docker container, which slims down the container by 80%:
```
$ docker images
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
fusion-alpine           latest    5a82f0e01a3c   45 years ago   37.1MB
fusion-debian           latest    b2d88472f6ef   45 years ago   179MB
```
=> Switch Docker image to use Alpine Linux

api/session.go
We are currently ignoring the error when we create a new session for a user. I don't see any reason to ignore the error, as the value of the Session object is undefined unless err == nil.
This change updates the code so that we return an error if `session.Get` returns a non-nil error code.
=> Check for error on creating a session

api/api.go, api/session.go
fusion's existing session handling logic is a bit incorrect but it still works due to workarounds.
sessions.NewCookieStore is supposed to receive a secure, random value:
https://pkg.go.dev/github.com/gorilla/sessions#section-readme
fusion currently passes it a fixed string baked into source. The result is that an attacker can forge a valid session token (they know the secret key) and send it to a fusion server, and the server would accept it.
The reason this isn't a problem right now is that fusion works around this by storing an additional copy of the password in the session and then checking the password on each authenticated request.
The current implementation works, but I think it's a bit more dangerous and complicated than what's ideal. Ideally, an attacker shouldn't be able to forge …
=> Simplify password authentication

repo/item.go
I propose reordering the list of items to be primarily based on publication date. Otherwise, if you add a new feed with a long backlog of posts, everything in that feed jumps to the front of your queue, which is probably not what you want.
=> Order items by publication date

scripts.sh
I forgot to remove it as part of #39, but this is dead code now and is just a no-op since there are no more `go:generate` directives in the code.
=> Remove the gen command from scripts.sh

api/api.go, api/session.go, cmd/server/server.go, conf/conf.go, repo/repo.go
Fixes #47
This refactors how we manage the configuration settings. Instead of loading them in `conf` and then sharing a variable in `conf` as global state, we read the configuration once from the `main` package and then pass the settings directly to the packages that consume them.
This makes it easier to reason about the code, as there is no more global state for configuration.
=> Get rid of global state for config

api/api.go, api/session.go, conf/conf.go, repo/repo.go
It feels a bit messy that the entire program has write access to the configuration as a shared global object. Shared globals make it more difficult to reason about a program's behavior.
This rewrite reduces the problem a bit by making the shared global state read-only after the client calls conf.Load.
=> Make conf settings read-only

api/session.go
Currently, if the user logs in to the server with the correct password, they get a cookie called session-token. If the server's password changes, the server (correctly) responds with an HTTP 401 Unauthorized when the user tries to use the token associated with the old password.
The problem is that the server's HTTP 401 response doesn't tell the client's browser to delete the old session token cookie, so it keeps sending it on every request even though the server knows it's bad.
Currently, it doesn't cause any noticeable problems, but I'm working on a change that will affect the data that we store in the session token, so it can lock the user out even if they have the same password because the password will be correct but they'll be using a session token that's invalid.
=> Tell browser to delete invalid session tokens

api/api.go, api/session.go, auth/password.go, auth/password_test.go, cmd/server/server.go, conf/conf.go
fusion's current password mechanism is vulnerable to a timing attack:
https://en.wikipedia.org/wiki/Timing_attack
Because fusion checks passwords using simple [character-by-character string comparison](https://github.com/0x2E/fusion/blob/28d360a4e1b9876b38b4fcf251bff9d6de31f21b/api/session.go#L28), a password attempt that begins with the correct characters will take longer to evaluate than one that starts with incorrect characters. For example, if the correct password is `platypus123` then a password attempt of `plates` will take longer to evaluate than `spoons` because `plates` and `platypus` share a common prefix. An attacker who attempts the password `plates` will know that they likely have the correct prefix. The attacker can continue measuring timing of new password attempts and …
=> Check passwords based on hashes rather than plaintext

api/session.go
Resolves #53
This fixes a bug I accidentally introduced by misunderstanding the echo session package. I thought that calling session.Get would return an error if no session existed for the session token valule. It seems that instead, if a session doesn't exist, session.Get creates one on-demand.
To fix this, we have to check the IsNew field of the session to see if calling session.Get created this session on-demand or if this was a session that was previously created in the Create function.
I introduced this bug in #43.
=> Fix a session checking bug

frontend/src/lib/components/ItemList.svelte
This MR fixes [4] from #55 
- Fixes the pagination bug.
- When you select a feed for eg. feed A with 10 pages, and you are on the 10th page.
- Then you change the feed to another feed B, which has only 5 pages.
- The state remains in page 10 because of Feed A, and shows empty UI for feed B since it doesn't have 10th page.
[Before vs After](https://github.com/user-attachments/assets/4cd9a6d7-494c-4370-8084-6fff188bca47)
=> fix: redirect to page 1 when use changes feeds

frontend/src/lib/components/ui/pagination/pagination-next-button.svelte, frontend/src/lib/components/ui/pagination/pagination-prev-button.svelte
This MR addresses [2] from #55 
- Improves pagination in mobile so it doesn't break down.
This pull request includes updates to the pagination buttons in the `frontend/src/lib/components/ui` directory to improve their responsiveness and styling.
https://github.com/user-attachments/assets/491f45d4-9cb2-4e57-929c-1a629488f898
- Fixes the previous button on larger screens, previously (no pun intended) it used to look like this
=> fix: improve pagination button responsiveness

server/feed.go, service/pull/handle.go
If I understand correctly, the function fetches a single feed, so the name should be FetchFeed to reflect the function's purpose.
=> Rename pull.FetchFeeds to FetchFeed

repo/item.go, service/pull/handle.go, service/pull/pull.go
The verb 'Creates' is a bit inconsistent with the other verbs we're using like List, Get, and Update. Those are all imperative, whereas Creates is simple present tense. I think 'Insert' is the more appropriate name, as it's imperative and describes the action. 'Create' sounds as though it creates a single thing, whereas 'Insert' properly communicates that it can insert one or many.
=> Rename Item.Creates to Item.Insert

service/pull/handle.go, service/pull/handle_test.go
I thought it would be helpful to get unit test coverage for the feed fetch logic.
Currently, our logic is pretty simple, but I'd like fusion to eventually be able to support the If-Modified-Since HTTP header, so we don't force servers to send the same data over and over. At that point, extra testing will be especially helpful, but I thought it would be a good idea to get testing infrastructure in place now.
=> Add unit tests for pull.FetchFeed

service/pull/handle.go, service/pull/handle_test.go
There's some complexity to deciding whether or not to update a feed, and there will be even more if we add support for things like honoring the Retry-After response header. I thought it would be helpful to extract the decision to a dedicated function so that we can unit test it.
Note that this change adjusts the decision logic slightly. Previously, we'd skip a suspended feed even if the force parameter was set to true. Now, we'll check a suspended feed if the force parameter was true. I don't think this actually changes anything because it doesn't seem like the user can force a refresh on a suspended feed, but I just wanted to call attention to the change.
=> Add tests for deciding whether to update a feed

.github/workflows/release.yml, frontend/vite.config.ts, scripts.sh
This moves the logic for determining fusion's version string from git-based checks within the frontend build to outer-level build scripts.
It's tripped me up a few times that version string generation happens in the Vite build.
When someone forks a repo, they don't have the tags, so when they run `./scripts.sh build`, the build will fail with a confusing error about git describe.
This change adjusts the logic so that we determine the fusion version string in `scripts.sh` and in the `release.yml` workflow. It also makes it so that if no version string is available, the frontend defaults to 'unknown-version', which should prevent unnecessary headaches when running vite in dev mode.
This should also make it easier for distributions that want to package fusion, as they previously had to apply …
=> Pull version string detection out of the frontend build

service/pull/handle.go
Eliminating the failure variable simplifies this function a bit and makes the values in the function calls more obvious to the reader.
=> Get rid of failure variable in Puller.do

frontend/src/lib/components/ItemList.svelte
A workflow I've been relying on before the redesign was opening multiple tabs from the feed with <kbd>Ctrl</kbd>+<kbd>Left Click</kbd>. The redesign removed the `Visit Original Link` button with no apparent reason so I am re-introducing it with this PR.
| Before | After |
|-----------|---------|
|![Screenshot From 2025-03-14 10-13-21](https://github.com/user-attachments/assets/8e778c01-cfa1-4625-b124-1b6c7e6dee47)|![Screenshot From 2025-03-14 10-13-15](https://github.com/user-attachments/assets/dd507cb7-0962-44aa-a675-5444fea6be06)|
=> feat: add `ItemActionVisitLink` to `ItemList`

frontend/src/lib/api/favicon.ts
This PR allows [RSSHub](https://docs.rsshub.app/) feeds to show their original favicon instead of a placeholder. I've only added a handful of sites I regularly visit, but it should be trivial for someone else to add more.
|Before|After|
|-|-|
|![Screenshot From 2025-03-14 15-11-43](https://github.com/user-attachments/assets/c0c7b726-8754-4c20-8dba-e8b9126645b7)|![Screenshot From 2025-03-14 15-11-47](https://github.com/user-attachments/assets/b91bdd9c-ae0f-45a1-b43e-9e332c525a2d)|
=> feat: improve favicon logic for rsshub

service/pull/handle.go
In Puller.do, we decide isLatestBuild by comparing the feed's stored LastBuild field to the fetched UpdatedParsed value, but then at the end of the function, we store PublishedParsed as the LastBuild time for the feed.
This appears to be an error, so this change makes it so that we consistently use the fetched feed's UpdateParsed field as the value of the LastBuild.
=> Treat update time as feed build time consistently

frontend/src/lib/components/ItemActionMarkAllasRead.svelte, frontend/src/lib/components/ItemListPlaceholder.svelte, frontend/src/routes/(authed)/+page.svelte, frontend/src/routes/(authed)/+page.ts, frontend/src/routes/(authed)/all/+page.svelte, frontend/src/routes/(authed)/all/+page.ts, frontend/src/routes/(authed)/bookmarks/+page.svelte, frontend/src/routes/(authed)/bookmarks/+page.ts
- removed unused API calls (all were blocking)
- site now shows loading state instead of blocking until everything's loaded (async data fetching)
- `frontend/src/routes/(authed)/feeds/[id]/+page.svelte` has not been touched but I will follow up with another PR in the near future
- this PR was created to offset the performance regression introduced in #81
=> feat: improve page load time

frontend/src/lib/api/item.ts, frontend/src/routes/(authed)/+page.ts, frontend/src/routes/(authed)/all/+page.ts, frontend/src/routes/(authed)/bookmarks/+page.ts, frontend/src/routes/(authed)/feeds/[id]/+page.ts
- reduce modification of `const` variable after its definition
- definition of `filter` happens in single operation rather than multiple
=> refactor: improve `filter` definition readability

frontend/src/lib/components/Sidebar.svelte
The feeds by default seem to be ordered by domain, which is not what the user might expect.
This switches the feed to be ordered by feed name.
Fixes #71
=> Sort feeds by name

service/pull/handle.go, service/pull/parse.go, service/pull/parse_test.go
The feed ID doesn't really belong in ParseGoFeedItems because its job is to convert gofeed objects to fusion objects, but the feed ID is not a concept in gofeed.
The only reason we need to store the feed ID in each feed item is so that each feed item references its parent feed in the database, so we should handle populating feed ID with the database logic, not with the gofeed parsing logic.
=> Remove feed ID from ParseGoFeedItems

service/pull/client/client.go, service/pull/client/client_test.go, service/sniff/wellknown.go
The sniff package uses redundant RSS parsing logic that duplicates logic that's in the service/pull/client package now.
This change adds a FetchDeclaredLink method that exposes functionality that the sniff package needs and switches the sniff.parseRSSUrl to use the client package instead of duplicating RSS parsing functionality.
=> Add FeedClient.FetchDeclaredLink method

pkg/httpx/httpx.go, pkg/httpx/request.go
We don't use these symbols outside of the httpx package, so we should unexport them to reduce the surface area of the package.
=> Unexport httpx.NewClient and httpx.transportOptionFunct

pkg/httpx/request.go, service/pull/client/client.go, service/pull/client/client_test.go, service/sniff/page.go, service/sniff/service.go
FusionRequest currently specifies model.FeedRequestOptions as a pointer rather than as a regular parameter. This is unnecessary, as it's easy for us to treat model.FeedRequestOptions{} as the 'default options' value. With it as a pointer, we clutter our code with extra != nil checks.
This change updates FusionRequest to just take a model.FeedRequestOptions rather than a *model.FeedRequestOptions.
=> Change FusionRequest to use a non-pointer type parameter

service/pull/handle.go, service/pull/singlefeed.go, service/pull/singlefeed_test.go
This is continuing my work on [refactoring Puller](https://github.com/0x2E/fusion/pull/84#issuecomment-2727600380) to reduce its complexity and to get its functionality under test.
This change creates a `SingleFeedPuller` that just handles pulling a single feed and storing the results of the pull in the data store. 
This refactoring allows us to get more of the feed logic under test, and we can test that we're doing the right thing in cases like where fetching the feed fails or storing the results in the data store fails.
One thing that still feels a bit hacky is how we manage the feed ID. It feels out of place that `defaultSingleFeedRepo.InsertItems` is responsible for populating the feed ID on each item. I'd eventually like to keep refactoring that so that `SingleFeedPuller` just never …
=> Refactor Puller to create a separate SingleFeedPuller

frontend/svelte.config.js
While browsers are able to fetch resources in limited parallel, it can still cause some delays when there are too many files.
=> refactor: switch to single bundle strategy

service/pull/client/client_test.go
I realized it's simpler to just create the actual error type in the testcase than to define the error message and wait until the test body to convert it to an error type.
=> Convert httpErrMsg to httpErr

service/pull/client/client_test.go
Strangely, my LLM coding assistant gets confused and hangs when it encounters the `<invalid>` and `<malformed>` tags in our testcases. This just switches it to more obviously invalid tags that are less likely to trip up LLMs.
=> Switch to more obviously invalid XML

model/feed.go, service/pull/backoff.go, service/pull/backoff_test.go, service/pull/handle.go, service/pull/handle_test.go, service/pull/singlefeed.go
The current implementation stops attempting to fetch a feed if fusion encounters any error fetching it. The only way to continue fetching the feed is if the user manually forces a refresh.
This allows fusion to recover from feed fetch errors by tracking the number of consecutive failures and slowing down requests for consistent failure. If a feed always fails, we eventually slow to only checking it once per week.
Fixes #67
=> Recover after feed fetch failure with exponential backoff

frontend/src/lib/components/FeedActionRefresh.svelte, frontend/src/lib/components/ItemActionBookmark.svelte, frontend/src/lib/components/ItemActionMarkAllasRead.svelte, frontend/src/lib/components/ItemActionUnread.svelte, frontend/src/lib/components/ItemList.svelte, frontend/src/routes/(authed)/+page.ts, frontend/src/routes/(authed)/all/+page.ts, frontend/src/routes/(authed)/bookmarks/+page.ts, frontend/src/routes/(authed)/feeds/[id]/+page.ts, frontend/src/routes/(authed)/feeds/[id]/ActionMenu.svelte, frontend/src/routes/(authed)/items/[id]/+page.ts, frontend/src/routes/(authed)/items/[id]/ItemSwitcher.svelte, frontend/src/routes/(authed)/search/+page.svelte, frontend/src/routes/(authed)/search/+page.ts
Didn't find an easy way to invalidate the load function of the `current` page, so use `page:{pathname}` as the key.
=> refactor: replace invalidateAll with invalidate for more granular cache control

service/pull/client/client.go, service/pull/client/parse.go, service/pull/client/parse_test.go
Some feeds use relative paths for the link field (e.g., "/item1" rather than "https://example.com/item1").
fusion's current behavior is to preserve the relative paths, but then when the user tries to click a link on one of these feeds, it sends the user to a non-existent path within fusion.
This fixes the interpretation of relative path links so that we automatically convert them back to absolute path URLs based on the feed URL.
Fixes #94
=> Handle feeds that use relative paths for links

service/pull/pull.go
fusion's previous behavior was to immediately retry requesting a feed when the request fails. This made more sense before we added failure recovery (df412f17d3fbb297d5a3753afa813d23d25731a3).
Now, immediately retrying on failure complicates the implementation and risks getting the client banned if the server is responding with HTTP 429 errors and we just keep spamming the same requests.
This change adjusts the polling behavior so that we only request each feed once per polling interval. If the request fails, we'll try again at the next polling interval.
=> Only pull feed once per polling interval

.env.example, README.md, api/api.go, auth/password.go, conf/conf.go
=> feat: make the password optional

.github/workflows/docker.yml
> [!IMPORTANT]
> You might need to make the container public once it's pushed to the registry. You should be able to do that [here](https://github.com/0x2E?tab=packages).
In addition to Dockerhub, images will also be published to GHCR. I also bumped the build push action to v6
Fixes: #135
=> ci: Publish container image to GitHub Container Registry

frontend/src/lib/api/item.ts, frontend/src/lib/components/ItemList.svelte, frontend/src/lib/components/Pagination.svelte, frontend/src/lib/components/Sidebar.svelte, frontend/src/routes/(authed)/groups/[id]/+page.svelte, frontend/src/routes/(authed)/groups/[id]/+page.ts, repo/item.go, server/item.go, server/item_form.go
=> feat: display items by group

frontend/src/lib/components/ItemActionShareLink.svelte, frontend/src/lib/components/ShortcutHelpModal.svelte, frontend/src/lib/i18n/langs/ca.ts, frontend/src/lib/i18n/langs/de.ts, frontend/src/lib/i18n/langs/en.ts, frontend/src/lib/i18n/langs/es.ts, frontend/src/lib/i18n/langs/fr.ts, frontend/src/lib/i18n/langs/pl.ts, frontend/src/lib/i18n/langs/pt-BR.ts, frontend/src/lib/i18n/langs/pt.ts, frontend/src/lib/i18n/langs/ru.ts, frontend/src/lib/i18n/langs/sv.ts, frontend/src/lib/i18n/langs/zh-Hans.ts, frontend/src/lib/i18n/langs/zh-Hant.ts, frontend/src/routes/(authed)/items/[id]/+page.svelte
This PR aims to solve #171 
- adds a new button to share the link of an item using native [navigator.share](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) API
- only shows the button when share API is supported
- ~~adds a shortcut (s)~~
- @0x2E would you prefer a different key, or no shortcut at all?
- add localizations for en+de, others missing
- who can provide translations for other languages? google translate? 🙂
=> add share action for items.
